pipeline:
  build:
    image: docker
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock 
    commands:
      - echo "test"
      - docker build -t trappentgmg/timr:$DRONE_COMMIT_SHA .
  test:
    image: trappentgmg/timr:$$DRONE_COMMIT_SHA
    commands:
      - pip3 install pytest
      - python3 -m pytest
